### ISSUE TITLE
(...)

### ISSUE THREAD

**Issue by enigma-watcher** [Sorackb/sinesp-api#10]
![screenshot_20180813-101320_sinesp cidadao](https://user-images.githubusercontent.com/42346260/44037397-9b622230-9eea-11e8-8c58-8f2214a3b120.jpg)

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.

resolves #10

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.

closes #10

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.

**Comment by Sorackb** [comment]
A [**Lei nº 12.527/2011**](http://www.planalto.gov.br/ccivil_03/_ato2011-2014/2011/lei/l12527.htm) regulamenta o direito constitucional de acesso às informações públicas, portanto o SINESP deveria disponibilizar uma API pública para obtenção dos dados em questão e a informação destacada conflita com a lei citada.
Em contrapartida o módulo em questão é apenas uma ferramenta para a obtenção dos dados e a utilização é de responsabilidade do utilizador. O módulo em si não realiza nenhuma divulgação, comercialização ou transmissão a terceiro.
