### ISSUE TITLE
Ajuda no uso da API

### ISSUE THREAD

**Issue by guifagotti** [Sorackb/sinesp-api#102]
Bom dia, instalei a API via NPM porem não estou conseguindo utilizar a mesma. 

Teria algum tutorial ou exemplo de como enviar as solicitações ?

Estou fazendo um projeto de faculdade e quero instalar a mesma em um servidor NODE e enviar as requisições através de um APP desenvolvido em React Native, normalmente é só fazer um fetch dentro do react para uma URL com a API mas nesse caso não sei como proceder.

Grato

**Comment by Sorackb** [comment]
Boa tarde @guifagotti. Você pode conferir um exemplo de implementação REST utilizando o módulo no projeto [sinesp-server](https://github.com/Sorackb/sinesp-server).

**Comment by guifagotti** [comment]
> 
> 
> Boa tarde @guifagotti. Você pode conferir um exemplo de implementação REST utilizando o módulo no projeto [sinesp-server](https://github.com/Sorackb/sinesp-server).

Boa tarde @Sorackb , tentei com o exemplo porem o retorno é sempre : 

object null is not iterable (cannot read property Symbol(Symbol.iterator))

a API está funcionando normalmente ??

**Comment by Sorackb** [comment]
> > Boa tarde @guifagotti. Você pode conferir um exemplo de implementação REST utilizando o módulo no projeto [sinesp-server](https://github.com/Sorackb/sinesp-server).
> 
> Boa tarde @Sorackb , tentei com o exemplo porem o retorno é sempre :
> 
> object null is not iterable (cannot read property Symbol(Symbol.iterator))
> 
> a API está funcionando normalmente ??

Na versão `2.0.1` está. Atualize a versão do módulo `sinesp-api` no seu `package.json`. Atualizei também o projeto [sinesp-server](https://github.com/Sorackb/sinesp-server) para a versão citada e executei os testes. Está tudo funcionando como o esperado.
