### ISSUE TITLE
Erro na consulta da placa CMJ5421

### ISSUE THREAD

**Issue by arsinoew** [Sorackb/sinesp-api#106]
@Sorackb , tudo bem?

Tive um problema que talvez vc consiga dar uma luz:
Placa CMJ5421, retorna dados no APP Sinesp porém não retorna dados (Error: sem dados na base) utilizando sua solução. Tem alguma ideia do  que pode estar acontecendo?

Seu endpoint salva vidas :-) Obrigado por mantê-lo! Quando estiver em SP já tem um almoço e uma rodada pagos, é só me avisar.

[responsesinesp.txt](https://github.com/Sorackb/sinesp-api/files/4731545/responsesinesp.txt)

**Comment by 100n0m3** [comment]
{
  "ano": "1998", 
  "anoModelo": "1998", 
  "chassi": "*****36819", 
  "codigoRetorno": "0", 
  "codigoSituacao": "0", 
  "cor": "Cinza", 
  "data": "10/06/2020 \u00e0s 09:29:50", 
  "dataAtualizacaoAlarme": "10/06/2020", 
  "dataAtualizacaoCaracteristicasVeiculo": "10/06/2020", 
  "dataAtualizacaoRouboFurto": "10/06/2020", 
  "marca": "GM", 
  "mensagemRetorno": "Sem erros.", 
  "modelo": "GM/CORSA SUPER", 
  "municipio": "SAO MIGUEL ARCANJO", 
  "placa": "CMJ5421", 
  "situacao": "Sem restri\u00e7\u00e3o", 
  "uf": "SP"
}

funcionando jovem

**Comment by 100n0m3** [comment]
lembrando que existe um limite na apicarros por ip.
