### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by luispimenta** [Sorackb/sinesp-api#107]
Olá. O link apicarros.com esta retornando ao consultar :

https://apicarros.com/v1/consulta/crv4745

ERR_CONNECTION_REFUSED

Será que quebrou algo ?

**Comment by arsinoew** [comment]
Você testou de novo? Está normal aqui.

**Comment by luispimenta** [comment]
Olá, sim, hoje cedo estava ok, muito obrigado.
