### ISSUE TITLE
Token = INVALID_SENDER

### ISSUE THREAD

**Issue by lrauseo** [Sorackb/sinesp-api#108]
Ao executar a pesquisa retorna o erro
TypeError: FIREBASE_ID.exec is not a function or its return value is not iterable.
Entrei nos modulos e na requisicao do token no metodo "getFirebaseToken"  retorna a mensagem "INVALID_SENDER"

Codigo utilizado
```
const sinesp = require('sinesp-api');

sinesp.search('axj9457')
        .then(function (response) {
            console.log(response);
        }).catch(function (err) {
            console.log(err.toString())
        });
```

**Comment by Sorackb** [comment]
Qual a versão do módulo que você está utilizando?

**Comment by lrauseo** [comment]
Agora que você perguntou eu acabei de ver que estava na 1.5.3, atualizei para a 2.0.1 e funcionou.
