### ISSUE TITLE
Limite de requests por IP?

### ISSUE THREAD

**Issue by Joao-PauloTI** [Sorackb/sinesp-api#109]
Olá!
Vocês saberiam me dizer qual o limite de requests que podem ser feitos por IP?
E quanto tempo leva até o limite resetar?
Obrigado.

**Comment by luiscastelli** [comment]
Se não me engano 1 request por IP a cada 60 segundos.

Em dom, 26 de jul de 2020 16:19, Joao-PauloTI <notifications@github.com>
escreveu:

**Comment by Joao-PauloTI** [comment]
Beleza então, valeu!
