### ISSUE TITLE
Atualizaram o app

### ISSUE THREAD

**Issue by Kkshi28** [Sorackb/sinesp-api#79]
mudou a url para v5 no final mas acho que mudaram algo mais no secret pois não esta funcionando

**Comment by Kkshi28** [comment]
url mudou para /sinesp-cidadao/mobile/consultar-placa/v5.
libs para o android mudaram de nome e secret gerando a chave do envelope diferente.
foi adicionado no cabeçalho da requisição uma chave de autenticação "Authorization: Token ffwFPHnPFz8:APA91bGsyyaPKKq7gbrKfynrj5CBG8hV3X46KiQ1cGaZpJV8xAG2_Xu7TIXOc-WKmYbXPOvGsjQom1IVnftnm11VnKOq-uL9CASHRRTjzdDCVrfzaMa6GbiaCpoPwCXD9Bba22dJi-qv"
foi adicionado uma chave no envelope da requisição, nesta chave está indo um código que também vai no authorization do cabeçalho, no meu caso ffwFPHnPFz8 e no cabeçalho "Authorization: Token ffwFPHnPFz8:APA..........".
alguém tem alguma ideia do que seria essa chave e de onde está saindo este cabeçalho de autenticação?

**Comment by theclanks** [comment]
Parece ser um JWT

**Comment by theclanks** [comment]
Esse maior é a placa em um base64ToHex.

**Comment by carloscte** [comment]
Alguém conseguiu? Obteve alguma novidade?

Pelo que eu pude ver, eles de fato estão utilizando o **FirebaseInstanceId** para obter o ID e o **TOKEN**, gerando assim o cabeçalho da requisição:
```
Authorization: Token TOKEN
```
Além da, como já foi citado, alteração da URL para https://cidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v5

Vi também que isso não é algo ligado diretamente com a chave de assinatura, ou seja, se você descompilar e compilar novamente o Apk do SINESP e utilizar uma chave qualquer para assinar o pacote, o aplicativo vai continuar funcionando.

@theclanks Acredito que esse maior seja o TOKEN. Não se trata da placa em base64ToHex não.

**Comment by Kkshi28** [comment]
@theclanks é do FirebaseId e esta relacionado com a instalação do app

**Comment by jhonata-menezes** [comment]
> Alguém conseguiu? Obteve alguma novidade?
> 
> Pelo que eu pude ver, eles de fato estão utilizando o **FirebaseInstanceId** para obter o ID e o **TOKEN**, gerando assim o cabeçalho da requisição:
> 
> ```
> Authorization: Token TOKEN
> ```
> 
> Além da, como já foi citado, alteração da URL para https://cidadao.sinesp.gov.br/sinesp-cidadao/mobile/consultar-placa/v5 e das libs para android.
> 
> Vi também que isso não é algo ligado diretamente com a chave de assinatura, ou seja, se você descompilar e compilar novamente o Apk do SINESP e utilizar uma chave qualquer para assinar o pacote, o aplicativo vai continuar funcionando.
> 
> @theclanks Acredito que esse maior seja o TOKEN. Não se trata da placa em base64ToHex não.

Segue solução para obter o Token
https://github.com/chapeupreto/sinesp/issues/37#issuecomment-508301473

**Comment by victor-torres** [comment]
Estou disponibilizando uma prova de conceito com uma nova de automatizar as consultas ao SINESP. É uma forma não invasiva e não depende de engenharia reversa do aplicativo. https://github.com/victor-torres/sinesp-bot

**Comment by diegolsr** [comment]
então a essa API não está mais funcionando?

**Comment by thiagocavalcanti** [comment]
Alguém conseguiu usar por esses dias? Testei a api e deu "Erro no processamento da consulta."

**Comment by vhenckel** [comment]
Parou de funcionar novamente @thiagocavalcanti

**Comment by JAAFSANTOS** [comment]
Para mim está aparecendo Error: Instalação inválida. Tente novamente ou re-instale o aplicativo.
