### ISSUE TITLE
--tls-min-v1.0

### ISSUE THREAD

**Issue by erikhenriq** [Sorackb/sinesp-api#84]
Não consegui configurar `--tls-min-v1.0` conforme mencionado para versões +11 do Node. Desculpa mas me parece um pouco confuso até na própria documentação do Node. Solicito mais uma ajuda e quem sabe também para deixar melhor documentado.. Obrigado pela lib, simples e poderosa!

**Comment by Sorackb** [comment]
Você só precisa adicionar o argumento `--tls-min-v1.0` na execução do `Node`. Um exemplo é o seguinte:

    node --tls-min-v1.0 index

**Comment by erikhenriq** [comment]
Obrigado @Sorackb!
`node index.js  --tls-min-v1.0`
