### ISSUE TITLE
TypeError: FIREBASE_ID.exec is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by petreg** [Sorackb/sinesp-api#99]
Ao usar a API esta dando este erro na linha 209 do index.js da API.
O estranho é que começou ontem ( pelo que notei )

Erro completo: 

 UnhandledPromiseRejectionWarning: TypeError: FIREBASE_ID.exec is not a function or its return value is not iterable
    at generateBody (/Users/petreg/Sites/sinesp/node_modules/sinesp-api/index.js:209:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sandrolborges** [comment]
Também estou com o mesmo problema,

**Comment by yrflx** [comment]
Aqui também caiu :s

**Comment by rodrigopmaciel** [comment]
Está quebrando com este erro internamente: Error=TOO_MANY_REGISTRATIONS

**Comment by caiquejjx** [comment]
Aqui também, pode ser deviado a alguma atualização por parte do Sinesp Cidadao

**Comment by petreg** [comment]
> Está quebrando com este erro internamente: Error=TOO_MANY_REGISTRATIONS

Recebi este mesmo erro no lugar do token do Firebase.
Será que a conta em questão está limitada?

**Comment by nhubner** [comment]
Aqui está dando esse erro também:

UnhandledPromiseRejectionWarning: TypeError: FIREBASE_ID.exec is not a function or its return value is not iterable

**Comment by petreg** [comment]
Pelo jeito foi largado de mão, realmente uma pena...

**Comment by yrflx** [comment]
Provavelmente, o Error=TOO_MANY_REGISTRATIONS ocorre devido a muitos 'registros' no mesmo ID de device, definidos em firebaseTools.js.

Precisamos de um novo código desses, se o dev tiver como ensinar para nós seria ótimo.

**Comment by samuelterra22** [comment]
Estou com o mesmo erro!

**Comment by pedrolucasdsc** [comment]
Alguém conseguiu outro meio de obter dados de veiculo?

**Comment by osor1o** [comment]
> Alguém conseguiu outro meio de obter dados de veiculo?

https://github.com/100n0m3/API-Carros
